### ISSUE TITLE
pycipapi authentication error when users have a different tennant id

### ISSUE THREAD

**Issue by NMNS93** [NHS-NGS/JellyPy#29]
A default tennant ID is currently part of the authentication URL in pycipapi config. Users that aren't registered with this tennant ID receive an error. We need a way to pass tennant details into the config/arguments and build the auth URL.

Authentication Error: {auth_response}’)
Exception: Authentication Error: {‘error’: ‘unauthorized_client’, ‘error_description’: “AADSTS700016: Application with identifier ‘12345’ was not found in the directory ‘a21-b21-c21’.

**Comment by andyb3** [comment]
Everyone should be using the same tenants (those specified in the config file) so don't think this is necessary
