### ISSUE TITLE
Create setup.py for easier sharing

### ISSUE THREAD

**Issue by s-boardman** [NHS-NGS/JellyPy#9]
I think it would help to create a setup.py to aid the distribution of JellyPy for new users.

This will help standardise installation procedures and with some careful construction ease maintenance of the modules and scripts that call them.

[Starting guide](https://github.com/kennethreitz/setup.py)

**Comment by aledj2** [comment]
Shall we try going down the JEP route with this?

**Comment by s-boardman** [comment]
Ooh yes, I totally forgot those existed. :man_facepalming:

**Comment by qwerty155** [comment]
I haven't created a JEP, but I thought a good starting point for this is here: https://github.com/NHS-NGS/JellyPy/pull/13.
Let me know what you think.
